#server:
#  port: 3004
#
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: transaction-alert-group
#      auto-offset-reset: latest
#      enable-auto-commit: true
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.value.default.type: com.toufik.trxalertservice.model.TransactionWithMT103Event
#        spring.json.trusted.packages: "*"
#        spring.json.use.type.info.headers: false


server:
  port: 3004

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-alert-group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.toufik.trxalertservice.model.TransactionWithMT103Event
        spring.json.trusted.packages: "*"
        spring.json.use.type.info.headers: false

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:toufik.saadane@gmail.com}
    password: ${GMAIL_APP_PASSWORD:qwya rjbf uaac vbne}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

# Custom Fraud Detection Configuration
fraud:
  email:
    enabled: true
    recipient-email: toufik.saadane@gmail.com
    sender-email: ${FRAUD_SENDER_EMAIL:fraud-alert@yourcompany.com}
    sender-name: "Transaction Fraud Alert System"
    subject: "🚨 FRAUD ALERT - Suspicious Transaction Detected"